plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.musictrigger'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.musictrigger"
        minSdk 21
        targetSdk 34
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}